### ISSUE TITLE
Clarity regarding installation of publisher NPM packages

### ISSUE THREAD

**Issue by drewkht** [electron-forge/electron-forge-docs#1]
Hi,

I'm a novice to JavaScript/Electron development and have been working on getting my first Electron app up and running using the Electron Forge v6 beta and this documentation. 

It's very possible it was just due to my lack of experience/knowledge regarding the Node environment, but it took me hours of reading and web searching to figure out that the reason I was getting the error "publisher target not found" when trying to use Electron Forge to publish to GitHub releases was because I had configured the publisher in package.json but hadn't installed the @electron-forge/publisher-github NPM package as well.

I've double checked the documentation trying to find any mention of this, and restarted a test project from scratch following the "Getting Started" section to try to confirm it wasn't that I just missed something.

Is there a step I should've taken to install that dependency after configuring the publisher in package.json  (another execution electron-forge init or something) that I missed in the existing documentation? Or is this the sort of a thing a more experienced dev would've known to go install as soon as they read the documentation regarding configuring the publisher in package.json?

Either way, just thought I'd ask for my own benefit and maybe that of anyone else going through something similar.

Thanks!

**Comment by drewkht** [comment]
As a side note, if it's useful - the way I finally discovered the solution was by reading through an existing issue in the EF GitHub where you showed an example of your package.json and I noticed you had @electron-forge/publisher-github listed as a dev dependency.

**Comment by Kingodbug** [comment]
> Hi,
> 
> I'm a novice to JavaScript/Electron development and have been working on getting my first Electron app up and running using the Electron Forge v6 beta and this documentation.
> 
> It's very possible it was just due to my lack of experience/knowledge regarding the Node environment, but it took me hours of reading and web searching to figure out that the reason I was getting the error "publisher target not found" when trying to use Electron Forge to publish to GitHub releases was because I had configured the publisher in package.json but hadn't installed the @electron-forge/publisher-github NPM package as well.
> 
> I've double checked the documentation trying to find any mention of this, and restarted a test project from scratch following the "Getting Started" section to try to confirm it wasn't that I just missed something.
> 
> Is there a step I should've taken to install that dependency after configuring the publisher in package.json (another execution electron-forge init or something) that I missed in the existing documentation? Or is this the sort of a thing a more experienced dev would've known to go install as soon as they read the documentation regarding configuring the publisher in package.json?
> 
> Either way, just thought I'd ask for my own benefit and maybe that of anyone else going through something similar.
> 
> Thanks!

bug fix auto arrange wifi
