### ISSUE TITLE
Missing Squirrel Config information - Icon

### ISSUE THREAD

**Issue by mix3d** [electron-forge/electron-forge-docs#10]
https://js.electronforge.io/maker/squirrel/interfaces/makersquirrelconfig#iconurl
This references `iconUrl`, but not `icon`. 

Because `iconUrl` expects a remote http/https url string, builds will fail when pointed to a local file.
see: https://github.com/electron-userland/electron-installer-windows/issues/55#issuecomment-390409854

This should note that only one of `[iconUrl, icon]` should be used, and `icon` for local app icon files.

**Comment by malept** [comment]
`electron-installer-windows` isn't used in Electron Forge, `electron-winstaller` is.

**Comment by mix3d** [comment]
Then why was my app still failing to build when I was using iconUrl with a local path?
`iconUrl: "./assets/app.ico"`
>"Invalid URI: The format of the URI could not be determined."

If I try `iconUrl: "file://./assets/app.ico"`, I get
>The 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd:iconUrl' element is invalid - The value 'file://./assets/app.ico' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:anyURI' - The string 'file://./assets/app.ico' is not a valid Uri value.

**Comment by malept** [comment]
`iconUrl` is described here: https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/docs/using/nuget-package-metadata.md#L15

**Comment by mix3d** [comment]
Then I would suggest including the very much important bit of information:

>"Note that the icon is fetched at installation time rather than packaging"

thus requiring this to be a fully qualified URL publicly available.

**Comment by malept** [comment]
I think you're looking for `setupIcon`: https://github.com/electron/windows-installer#usage

Also https://js.electronforge.io/maker/squirrel/interfaces/makersquirrelconfig#setupicon

**Comment by mix3d** [comment]
Nope, I am looking for the icon for the application itself, that is displayed on the EXE and in the installed application menu.
![image](https://user-images.githubusercontent.com/1474137/85478951-0d2a5a00-b572-11ea-8293-5d1f695b5285.png)

Without an iconUrl, I get the default app icon on install:
![image](https://user-images.githubusercontent.com/1474137/85479060-49f65100-b572-11ea-8835-e0cc2dec97a3.png)

What your Squirrel.Windows link says, is that it is grabbed _at installation time_, which means (unless I'm reading it wrong) it needs to be a fully qualified URL and accessible via internet. (Which is honestly REALLY annoying for offline installs)

See:
https://github.com/electron/windows-installer/issues/151
https://github.com/electron/windows-installer/issues/56

**Comment by malept** [comment]
> (Which is honestly REALLY annoying for offline installs)

Perhaps you want the WiX MSI maker instead.

**Comment by mix3d** [comment]
Either way, I would strongly encourage the docs to reflect this strict publicly hosted URL requirement.

**Comment by malept** [comment]
Feel free to submit a pull request to adjust the docs here: https://github.com/electron/windows-installer/blob/ce04bd0e13872d9a8cf7c7a507949c53a6732dfc/src/options.ts#L82-L87
