### ISSUE TITLE
electron-forge Content Security Policy

### ISSUE THREAD

**Issue by kirbystudy** [electron-forge/electron-forge-docs#107]
In the vue project, I introduced the image link url. After the electron-forge package, the electron-forge start chrome developer tool console reported an error message 
![image](https://user-images.githubusercontent.com/63231787/222873389-01dd7f3d-fd70-4b44-9b9a-05bf10b68ac5.png)

**Comment by erickzhao** [comment]
If you're using the webpack plugin: https://www.electronforge.io/config/plugins/webpack#devcontentsecuritypolicy

**Comment by kirbystudy** [comment]
Okay, thank you!!!
