### ISSUE TITLE
Sync issues with GitBook

### ISSUE THREAD

**Issue by malept** [electron-forge/electron-forge-docs#11]
Since the repository was moved, merged PRs aren't showing up in GitBook, and changes made inside the GitBook UI aren't being synced here. This means that the docs cannot be changed in either place until we figure out how to fix that.

**Comment by b-zurg** [comment]
Have the basics been checked? https://docs.gitbook.com/integrations/github/faq

**Comment by mahnunchik** [comment]
ping

**Comment by mahnunchik** [comment]
@malept let's drop GitBook support as it is blocks so many PRs.

**Comment by mahnunchik** [comment]
Hi All @malept @MarshallOfSound 

It is not funny! It seems a lot of PR are blocked by this sync issue. At least my PR:

* https://github.com/electron-userland/electron-forge/pull/1761
* https://github.com/electron-userland/electron-forge/pull/1752
* https://github.com/electron-userland/electron-forge/pull/1785

How can I help you to have this PR merged?

**Comment by mahnunchik** [comment]
ping

**Comment by kethan1** [comment]
@mahnunchik the electron-forge docs are made with GitBook, so you can't drop support for it.

**Comment by mahnunchik** [comment]
@kethan1 PR is waiting half a year to be merged because the issue with documentation framework 🤦

**Comment by kethan1** [comment]
Huh, my pr of adding 1 comma (very small) showed up. Was is manually edited in GitBook (dunno how GitBook works never used it), or is syncing working?

**Comment by erickzhao** [comment]
I think this is closed.
