### ISSUE TITLE
Shorthand properties not work

### ISSUE THREAD

**Issue by yyyykl** [electron-forge/electron-forge-docs#118]
![image](https://user-images.githubusercontent.com/46413767/233108722-917597aa-05c2-4ecc-bdf1-0e4ced70d5a1.png)
When I use `electron ./`  this is work, but when I use` electron-forge start` this become unknown property name.

```
const createWindow = () => {
  const win = new BrowserWindow({
    width: 1600,
    height: 700,
    webPreferences: {
      preload: path.join(__dirname, 'rpc/bridge.js'),
      // contextIsolation: false,
      nodeIntegration: false,
      // plugins: true,
    },
  });

  win.loadURL("http://127.0.0.1:889/")
};
```

**Comment by erickzhao** [comment]
I don't think CSS issues are related specifically to Forge.

A minimal repro would be good, but I think I'll close this out for now.
