### ISSUE TITLE
VS Code Debug Instructions Are Wrong

### ISSUE THREAD

**Issue by owo** [electron-forge/electron-forge-docs#125]
Frankly, I don't know whether to post this issue on [forge](https://github.com/electron/forge) or [electron-forge-docs](https://github.com/electron-forge/electron-forge-docs), but there's a misunderstanding in both repos.

The instructions for [Debugging with VS Code](https://www.electronforge.io/advanced/debugging#debugging-with-vs-code) will not work because of the way `electron-forge-vscode-nix` works.

The issue is with the following line:
```
    "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron-forge-vscode-nix",
```

The problem is that `${workspaceFolder}/node_modules/.bin/electron-forge-vscode-nix` is a symlink to `${workspaceFolder}/node_modules/@electron-forge/cli/script/vscode.sh` and it tries to determine the project directory by referencing it relative to it's own path. Thus, the symlink and the original script will run `electron-forge-start` in different working directories.

Replacing the above line with the following will work:
```
    "runtimeExecutable": "${workspaceFolder}/node_modules/@electron-forge/cli/script/vscode.sh",
```

I'm not sure if the Windows version of this option has this issue.

**Comment by erickzhao** [comment]
Fixed in https://github.com/electron-forge/electron-forge-docs/commit/344b7b32be7023c86868406cda14b0044d5bc27a https://github.com/electron-forge/electron-forge-docs/commit/590831e8c5521695e7397877871098d64bcc7117
