### ISSUE TITLE
Missing minimum requirements

### ISSUE THREAD

**Issue by phillippschmedt** [electron-forge/electron-forge-docs#16]
The website provides no clear information on what electron-forge depends on.

~~For example yarn 2 is required to run:~~

~~`yarn dlx @electron-forge/cli import`~~

~~see:  https://www.electronforge.io/import-existing-project~~

**Comment by ghost** [comment]
Yes. Forge is missing a lot of docs. PRs welcome!

**Comment by phillippschmedt** [comment]
@malept has fixed the example I was mentioning. I still wonder if it makes sense to add the minimum requirements.

**Comment by malept** [comment]
Running Forge itself should tell you its own minimum requirements. What didn't work?

**Comment by ghost** [comment]
Malept is the most active here. I met him on the Discord. Good job @malept . Anyway, I don't understand your issue

**Comment by phillippschmedt** [comment]
@malept  You had code in the docs that was not working. It said yarn when it actually required yarn 2. And the docs did not mention it. You updated the docs after I told you on discord about it. So this issue got fixed by you.  I still believe the docs should clearly name the requirements.
