### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by jgresham** [electron-forge/electron-forge-docs#170]
enable dark mode

**Comment by mdirfan40** [comment]
I am not able to see source code allow to access to work on it

**Comment by jgresham** [comment]
> I am not able to see source code allow to access to work on it

Right. I think the Electron Forge team just needs to enable it in Gitbook.

**Comment by jgresham** [comment]
@mdirfan40 looks like they may migrate to something open source https://github.com/electron-forge/electron-forge-docs/pull/176

**Comment by mdirfan40** [comment]
> @mdirfan40 looks like they may migrate to something open source #176

will it merge or not ?

**Comment by erickzhao** [comment]
<img width="281" alt="image" src="https://github.com/electron-forge/electron-forge-docs/assets/16010076/b55dbb9c-e0e2-41bc-8182-91bfe07fc767">

now available via the bottom right of the website
