### ISSUE TITLE
Make some mention of the fact that the barrier to entry for auto-updates using github is 1000 dollars

### ISSUE THREAD

**Issue by ChristopherJTrent** [electron-forge/electron-forge-docs#183]
It'd be wonderful if there was some mention that in order to use github as an auto-update provider, one would have to spend over 1000 dollars per year to form an LLC and get an EV signing certificate, (llc required because fun fact, nobody will issue an EV key to an individual)

**Comment by MarshallOfSound** [comment]
> It'd be wonderful if there was some mention that in order to use github as an auto-update provider, one would have to spend over 1000 dollars per year to form an LLC and get an EV signing certificate, (llc required because fun fact, nobody will issue an EV key to an individual)

This isn't true, on Windows you do not need a certificate in order to do auto updating. You never have. And if you want a certificate, you definitely don't need an EV one and you can definitely get certs for less than 1000 dollars.

On macOS you do and that costs 100 dollars a year but that's a requirement imposed by Apple and impacts _everyone_.

**Comment by ChristopherJTrent** [comment]
> > It'd be wonderful if there was some mention that in order to use github as an auto-update provider, one would have to spend over 1000 dollars per year to form an LLC and get an EV signing certificate, (llc required because fun fact, nobody will issue an EV key to an individual)
> 
> This isn't true, on Windows you do not need a certificate in order to do auto updating. You never have. And if you want a certificate, you definitely don't need an EV one and you can definitely get certs for less than 1000 dollars.
> 
> On macOS you do and that costs 100 dollars a year but that's a requirement imposed by Apple and impacts _everyone_.

Per your own documentation this is not true.

**Comment by ChristopherJTrent** [comment]
> > It'd be wonderful if there was some mention that in order to use github as an auto-update provider, one would have to spend over 1000 dollars per year to form an LLC and get an EV signing certificate, (llc required because fun fact, nobody will issue an EV key to an individual)
> 
> This isn't true, on Windows you do not need a certificate in order to do auto updating. You never have. And if you want a certificate, you definitely don't need an EV one and you can definitely get certs for less than 1000 dollars.
> 
> On macOS you do and that costs 100 dollars a year but that's a requirement imposed by Apple and impacts _everyone_.

Do you have any proof that an individual validation key will function for update.electronjs.org? They require signed code, hardline, so your comment that "you do not need a certificate to do auto updating" is not universally true.

**Comment by MarshallOfSound** [comment]
> Do you have any proof that an individual validation key will function for update.electronjs.org? They require signed code, hardline, so your comment that "you do not need a certificate to do auto updating" is not universally true.

Hi, I helped write update.electronjs.org, I'm a core electron maintainer, I've written code for squirrel.mac and squirrel.windows.

**There is no requirement on windows that your app be signed**

Is there a poorly documented part of update.electronjs.org that indicates a code signing certificate is required on windows? The only platform that requires code signing is macOS and that is a platform level requirement, not an updater requirement

**Comment by ChristopherJTrent** [comment]
https://github.com/electron/electron/blob/main/docs/tutorial/code-signing.md

Also the Requirements section of the README here: https://github.com/electron/update.electronjs.org

**Comment by MarshallOfSound** [comment]
That would have been a better place to start that arriving in this repo all confrontational. You're lucky I engaged instead of ignoring or blocking.

I'll bring this issue to the electron docs group and get the website updated. But please in the future reconsider your approach to open source projects, being antagonistic is not the right communication strategy.

**Comment by ChristopherJTrent** [comment]
Look, I'm sorry that I treated your organization's documentation as though it was accurate. I'll make sure to avoid that mistake in the future. Have a day.

________________________________

**Comment by VerteDinde** [comment]
@ChristopherJTrent, your comment was deleted as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md). You may consider this an official warning.

Please do not interact with the project for 24 hours. After that, you're welcome to continue any issues or discussions as needed, as long as they fall within the code of conduct guidelines. I understand that working with open source software can be frustrating, but please be kind and civil to the people who are trying to help maintain that software.
