### ISSUE TITLE
How can I set provider to generic in electron forge publish?

### ISSUE THREAD

**Issue by pejman1** [electron-forge/electron-forge-docs#20]
I have read all the document but I could not find any information to how can I set provider to generic in electron forge publish config

**Comment by malept** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

**Comment by pejman1** [comment]
> Thanks for reaching out!
> 
> The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I could not find anything about this issue in the aforementioned links.  It should be a feature in electron forge publish config not in other libs

**Comment by malept** [comment]
The point is that this issue tracker is not the place to ask questions about Forge config (or, for that matter, ask for feature requests for Forge). It's more appropriate to use the Electron community forums for usage questions.

That being said, there is no first party publisher plugin for Electron Forge to do "generic" publishing. It's such a undefined concept that I don't even know what the design would be.
