### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nikwen** [electron-forge/electron-forge-docs#200]
The keychain link here is broken: https://www.electronforge.io/guides/code-signing/code-signing-macos#option-3-using-a-keychain

**Comment by erickzhao** [comment]
Thanks for the report @nikwen! Unfortunately, it seems like this part of the Apple documentation for Keychain Access was gutted with the release of macOS Sequoia and the new Passwords app.

(see https://web.archive.org/web/20240428154408/https://support.apple.com/en-ca/guide/mac-help/mchlf375f392/mac for original docs)

Will replace/remove the link shortly.

**Comment by nikwen** [comment]
Thanks, @erickzhao!
