### ISSUE TITLE
Error in the documentation for adding install scripts to PKG

### ISSUE THREAD

**Issue by merwaaan** [electron-forge/electron-forge-docs#211]
There's [an example in the doc for adding install scripts to PKG](**url**).

The example incorrectly uses the `install` option instead of `scripts` (`install` is the default install location).

This produces installers that fail at the last step. I've been banging my head all day before noticing the typo. Fixing the doc might help some users :)

**Comment by erickzhao** [comment]
Hey @merwaaan, that's my bad. Thanks for reporting the issue. Docs fixed in https://github.com/electron-forge/electron-forge-docs/commit/50ddba5eedec76006408dd0a314798f16e4ad2ec.
