### ISSUE TITLE
How to configure in forge.config.js two different renderer processes?

### ISSUE THREAD

**Issue by raphael10-collab** [electron-forge/electron-forge-docs#26]
I need to open a second electron browserWindow, and I tried to configure in forge.config.js two different renderer processes:

    /* eslint-disable @typescript-eslint/no-var-requires */
    // Forge Configuration
    const path = require('path');
    const rootDir = process.cwd();

    module.exports = {
      // Packager Config
      packagerConfig: {
        // Create asar archive for main, renderer process files
        asar: true,
      },
      // Forge Makers
      makers: [
        {
          // Squirrel.Windows is a no-prompt, no-hassle, no-admin method of installing
          // Windows applications and is therefore the most user friendly you can get.
          name: '@electron-forge/maker-squirrel',
          config: {
            name: 'trial_ipc_2020',
          },
        },
        {
          // The Zip target builds basic .zip files containing your packaged application.
          // There are no platform specific dependencies for using this maker and it will run on any platform.
          name: '@electron-forge/maker-zip',
          platforms: ['darwin'],
        },
        {
          // The deb target builds .deb packages, which are the standard package format for Debian-based
          // Linux distributions such as Ubuntu.
          name: '@electron-forge/maker-deb',
          config: {},
        },
        {
          // The RPM target builds .rpm files, which is the standard package format for
          // RedHat-based Linux distributions such as Fedora.
          name: '@electron-forge/maker-rpm',
          config: {},
        },
      ],
      // Forge Plugins
      plugins: [
        [
          // The Webpack plugin allows you to use standard Webpack tooling to compile both your main process code
          // and your renderer process code, with built in support for Hot Module Reloading in the renderer
          // process and support for multiple renderers.
          '@electron-forge/plugin-webpack',
          {
            // Main process webpack configuration
            mainConfig: path.join(rootDir, 'tools/webpack/webpack.main.js'),
            // Renderer process webpack configuration
            renderer: {
              // Configuration file path
              config: path.join(rootDir, 'tools/webpack/webpack.renderer.js'),
             // Entrypoints of the application
              entryPoints: [
                {
                  // React Hot Module Replacement (HMR)
                  rhmr: 'react-hot-loader/patch',
                  // HTML index file template
                  html: path.join(rootDir, 'src/index.html'),
                  // Renderer
                  // https://www.electronjs.org/docs/tutorial/quick-start#main-and-renderer-processes
                  // https://github.com/electron-userland/electron-webpack/issues/47
                  //js: path.join(rootDir, 'src/renderer.ts'),
                  js: path.join(rootDir, ['src/renderer.ts', 'src/renderer-2.ts']),
                  // Main Window
                  name: 'main_window',
                  // Preload
                  preload: {
                    js: path.join(rootDir, 'src/preload.ts'),
                  },
                },
              ],
            },
          },
        ],
      ],
    };

And got this error:

    (base) marco@pc01:~/webMatters/electronMatters/trial-ipc$ yarn start
    yarn run v1.22.5
    $ cross-env NODE_ENV=development electron-forge start
    ✔ Checking your system
    ✔ Locating Application
    Failed to load: /home/marco/webMatters/electronMatters/trial-ipc/tools/forge/forge.config.js

    An unhandled rejection has occurred inside Forge:
    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
        at validateString (internal/validators.js:121:11)
        at Object.join (path.js:1039:7)
        at Object.<anonymous> (/home/marco/webMatters/electronMatters/trial-ipc/tools/forge/forge.config.js:66:24)
        at Module._compile (internal/modules/cjs/loader.js:1201:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
        at Module.load (internal/modules/cjs/loader.js:1050:32)
        at Function.Module._load (internal/modules/cjs/loader.js:938:14)
        at Module.require (internal/modules/cjs/loader.js:1090:19)
        at require (internal/modules/cjs/helpers.js:75:18)
        at _default (/home/marco/webMatters/electronMatters/trial-ipc/node_modules/@electron-forge/core/src/util/forge-
    config.ts:123:21)
        at _default (/home/marco/webMatters/electronMatters/trial-ipc/node_modules/@electron-forge/core/src/api/start.ts:37:23)
        at /home/marco/webMatters/electronMatters/trial-ipc/node_modules/@electron-forge/cli/src/electron-forge-start.ts:59:19 {
      code: 'ERR_INVALID_ARG_TYPE'
    }

    Electron Forge was terminated. Location:
    {}
    error Command failed with exit code 1.

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, consider using one of the [community forums](https://electronjs.org/community) (such as the [official Discord server](https://discord.gg/electron)), as there are more people there available to answer questions.
