### ISSUE TITLE
Configuration keywords have changed, undocumented and inconsistent doco

### ISSUE THREAD

**Issue by abulka** [electron-forge/electron-forge-docs#3]
The latest [electron-forge documention](https://www.electronforge.io/configuration) refers to  the `config.forge` path  in `package.json` containing `packagerConfig` and `makers`, whereas older versions of "Forge Config" contain `electronPackagerConfig`, `make_targets` and a variety of others like `electronRebuildConfig` and `electronInstaller*`.

The latest [doco on npm](https://www.npmjs.com/package/electron-forge) refers to the older configuration format:
```
{
  "make_targets": {
    "win32": ["squirrel"], // An array of win32 make targets
    "darwin": ["zip", "dmg"], // An array of darwin make targets
    "linux": ["deb", "rpm", "flatpak", "snap"] // An array of linux make targets
  },
  "electronPackagerConfig": {},
  "electronRebuildConfig": {},
  "electronWinstallerConfig": {},
  "electronInstallerDMG": {},
  "electronInstallerFlatpak": {},
  "electronInstallerDebian": {},
  "electronInstallerRedhat": {},
  "electronInstallerSnap": {}
}
```
which is inconsistent with the doco at www.electronforge.io

1. Why is the documentation inconsistent - is the older format somehow still supported in later versions of electron-forge, so it doesn't matter perhaps?
2. When exactly was the format change made and is there a migration guide? I couldn't find anything in my searching.
3. It would be helpful to have some additional hints about how electron-packager config meshes with "Forge Config".
4. The electron-forge [configuration examples](https://www.electronforge.io/configuration) are a mix of `package.json`, `module.exports` and `forge.config.js` format entries. Whilst it is nice that there are so many ways of achieving configuration, it might be better to have a consistent format for all the examples to avoid confusion.

## My Migration Notes
For my own project, I migrated by kind of figuring it out. I like the new format better. Here is what I did to my `package.json`:

- Renamed `electronPackagerConfig` -> `packagerConfig`
- Removed `make_targets`, `electronRebuildConfig` and all the `electronInstaller*`entries and replaced them with a single `makers` entry e.g. 

```
 "config": {
    "forge": {

      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": "myproject"
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {},
          "platforms": [
            "linux"
          ]
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
```
In addition, for what its worth, I read all the config examples for all the makers and compiled this list of possible keywords in each makers object:
```
- name
- platforms  (a list of strings)
- config 
    - name
    - background
    - format
    - options
        - maintainer
        - homepage
        - categories
        - mimeType
        - keychain
    - features
        - audio
        - mpris
        - webgl
    - summary
    - certificateFile
    - certificatePassword
```

As I mentioned in point 4 above, it would be helpful to have some indication of what exactly is allowed in each maker config object, and how that meshes (or not) with electron-packager documentation. Running `$(npm bin)/electron-packager --help` didn't, at first glance, give me any meshing ideas.

**Comment by chetbox** [comment]
Thank you @abulka! This is the most useful documentation I have found for maker config in 2021.

**Comment by chetbox** [comment]
Update: I found some helpful documentation [here](https://www.electronforge.io/config/makers) but I was thrown off by the out-of-date documentation on nmpjs.com: https://www.npmjs.com/package/electron-forge

**Comment by ghost** [comment]
> ## My Migration Notes
> For my own project, I migrated by kind of figuring it out. I like the new format better. Here is what I did to my `package.json`:
> 
> * Renamed `electronPackagerConfig` -> `packagerConfig`
> * Removed `make_targets`, `electronRebuildConfig` and all the `electronInstaller*`entries and replaced them with a single `makers` entry e.g.
> 
> ```
>  "config": {
>     "forge": {
> 
>       "makers": [
>         {
>           "name": "@electron-forge/maker-squirrel",
>           "config": {
>             "name": "myproject"
>           }
>         },
>         {
>           "name": "@electron-forge/maker-zip",
>           "platforms": [
>             "darwin"
>           ]
>         },
>         {
>           "name": "@electron-forge/maker-deb",
>           "config": {},
>           "platforms": [
>             "linux"
>           ]
>         },
>         {
>           "name": "@electron-forge/maker-rpm",
>           "config": {}
>         }
>       ]
> ```
> 
> In addition, for what its worth, I read all the config examples for all the makers and compiled this list of possible keywords in each makers object:
> 
> ```
> - name
> - platforms  (a list of strings)
> - config 
>     - name
>     - background
>     - format
>     - options
>         - maintainer
>         - homepage
>         - categories
>         - mimeType
>         - keychain
>     - features
>         - audio
>         - mpris
>         - webgl
>     - summary
>     - certificateFile
>     - certificatePassword
> ```
> 

Many thanks for this documentation! I don't understand why they never keep the documentations updated.

**Comment by erickzhao** [comment]
I think we caught most of these problems in the v6.0.0 stable release. Please open an issue (or submit a PR) if you find any new problems!
