### ISSUE TITLE
Help - Where can I find more documentation for configs in .compilerc 

### ISSUE THREAD

**Issue by mboutin-qohash** [electron-forge/electron-forge-docs#30]
Hi! 

I just want to know more about .compilerc file and how to manage it.

Thank you

**Comment by malept** [comment]
This issue tracker is for bugs and feature requests specifically relating to documentation.

That being said, `.compilerc` is an Electron Forge v5 concept and is not used in v6. I would recommend upgrading to v6 as soon as possible.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).
