### ISSUE TITLE
Debugging with VS Code - how exactly??

### ISSUE THREAD

**Issue by gfmoore** [electron-forge/electron-forge-docs#32]
I had high hopes that "Debugging your Electron main process through VS Code is ridiculously easy with Forge. Simply add this as a launch config in VSCode and you're good to go."

However, I am not finding it so.

The blurb says create a "launch.config" file (edit: It didn't, I assumed this.). This doesn't seem to do anything. I also tried a launch.json (what I have used before?), but when launching the debugger I get:
``` 
C:\Program Files\nodejs\node.exe .\src\index.js
Debugger attached.
Waiting for the debugger to disconnect...
c:\Users\Gordon\Documents\Applications\ElectronForgeTest\my-app\src\index.js:26
app.on('ready', createWindow);
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (c:\Users\Gordon\Documents\Applications\ElectronForgeTest\my-app\src\index.js:26:5)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
Process exited with code 1
null: Uncaught TypeError: Cannot read property 'on' of undefined
```

Yet, using the command line, the auto generated app runs fine.

Perhaps in my ignorance I am not doing what I should.

Could you please do a step by step. Where do I put the launch.config? In the root, in .vscode?
When I click on the debugging icon it asks for Run and Debug ( as well as other options) I would have thought (in my ignorance) that it would pick up the launch.config and start debugging. 
If it displays select environment, what do I select? Node, Node(legacy)? I would have hoped that Electron would show up?

Sorry, I am very conscious that I don't understand the process, but it certainly isn't trivial!! :)

**Comment by gfmoore** [comment]
Okay, figured this now. For the benefit of others:

Click on the run/debug icon (with the bug!)
Click on the create a launch.json file.
Select the node.js environment - though it doesn't matter I think as we will overwrite it
Copy the launch.config code in the readme example
Paste it into the launch.json so that you get   (Your sticking it under the part that says: "configurations": [
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron-forge-vscode-nix",
      "windows": {
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron-forge-vscode-win.cmd"
      },
      // runtimeArgs will be passed directly to your Electron application
      "runtimeArgs": [
        "foo",
        "bar"
      ],
      "cwd": "${workspaceFolder}"
    }
  ]
}
```

You should now be able to run/debug - without errors :)

I think on the initially created launch.json you can click on the add configuration and paste the launch.config code into that. Not sure why though?

**Comment by nzhul** [comment]
@gfmoore I just wanted to let you know that you are not the only one confused.
By reading their documentation I got the impression that I need to replace the whole launch.json file.
Your comment helped me, so big thanks!
