### ISSUE TITLE
error using `--template=typescript-wabpack` is `'createSnapshot' of undefined`

### ISSUE THREAD

**Issue by BananaAcid** [electron-forge/electron-forge-docs#33]
# problematic / unintuitive install ...

<img width="1180" alt="Bildschirmfoto 2021-02-04 um 20 20 20" src="https://user-images.githubusercontent.com/1894723/106944032-6bcdce00-6726-11eb-9587-791cf214e090.png">

installed und run -- as in the docs at `https://www.electronforge.io/advanced/extending-electron-forge`

# i figured, `electron-forge` would be missing ... so: 

![image](https://user-images.githubusercontent.com/1894723/106945806-8e60e680-6728-11eb-9e92-0eb93dbf2040.png)

# so next i went with installing the `dev` dep
![image](https://user-images.githubusercontent.com/1894723/106946642-a6853580-6729-11eb-989d-4065e2f6682c.png)

# next I did:

`notepad package.json` and removed the `^` in front of the version and `npm start` again

# ... finally it works ... but a lot of warnings and deprecation messages - audit-fix created even more errors

## what doesn't work: `npm run package` ... it compiles fine, but crashes on start.

<img width="702" alt="Bildschirmfoto 2021-02-04 um 23 17 18" src="https://user-images.githubusercontent.com/1894723/106962408-5dd87700-673f-11eb-974c-0823a0567975.png">

**Comment by malept** [comment]
I can't reproduce the first error:

```
❯ npx --no-install --ignore-existing create-electron-app --template=typescript-webpack test-ts-webpack && cd test-ts-webpack && yarn start
✔ Initializing Project Directory
✔ Initializing Git Repository
✔ Locating custom template: "typescript-webpack"
✔ Copying Starter Files
✔ Initializing NPM Module
✔ Setting up Forge configuration
✔ Setting up TypeScript configuration
✔ Installing Template Dependencies
✔ Installing NPM Dependencies
yarn run v1.22.5
$ electron-forge start
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Compiling Main Process Code
✔ Launch Dev Servers
✔ Compiling Preload Scripts
✔ Launching Application


Webpack Output Available: http://localhost:9000

(node:17403) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
webpack built 68589a9b56f245ffdecb in 432ms
Issues checking in progress...
No issues found.
Done in 13.73s.
```

I don't know why it would be trying to load webpack 5 things.

**Comment by BananaAcid** [comment]
Maybe the setup is incompatible with npm or something? You were using yarn, it seems. And npx with other params as in the electron-forge docs. I did reproduce it on different, freshly setup windows 10 machines in PowerShell (8 machines at our office, 2 at home) with the same error result when copy pasting the my commands above.

As you can see, I took screenshots of all steps.

Maybe you should add to the docs, that Windows10 / PowerShell / NPM is not supported.

**Comment by shadanan** [comment]
I have the same issue. MacOS + NPM.
