### ISSUE TITLE
Failed to create Win-Installer due to large application size

### ISSUE THREAD

**Issue by christopherGr** [electron-forge/electron-forge-docs#36]
Hello,

I am trying to create windows installer (squirrel, msi) for my large application which size is about more than 4gb (i had to embed many mp4 files into asar file) but i cannot, the setup.exe that is created is corrupted..if i delete embedded mp4 files everything is ok...
Is there any solution?

**Comment by malept** [comment]
This issue tracker is for bugs and feature requests in the documentation, not for support for creating Electron apps.

Instead, please use one of the [community forums](https://electronjs.org/community).
