### ISSUE TITLE
linux ubuntu icon invalid

### ISSUE THREAD

**Issue by tkggusraqk** [electron-forge/electron-forge-docs#38]
package.json
`
{
  "name": "zwt",
  "productName": "zwt",
  "version": "",
  "description": "zwt",
  "main": "src/index.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "eslint src --color"
  },
  "keywords": [],
  "author": "cxj",
  "license": "mit",
  "config": {
    "forge": "./forge.config.js"
  },
  "dependencies": {
    "electron-compile": "^6.4.4",
    "electron-squirrel-startup": "^1.0.0"
  },
  "devDependencies": {
    "babel-plugin-transform-async-to-generator": "^6.24.1",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "electron": "^12.0.1",
    "electron-forge": "^5.2.4",
    "electron-prebuilt-compile": "8.2.0",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.22.0"
  }
}
`
project url:https://github.com/tkggusraqk/electron-demo.git

**Comment by malept** [comment]
This repository is not used for questions, but for bugs and feature requests for the documentation.

If you still need assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).
