### ISSUE TITLE
eslint(import/no-unresolved) in react with typescript framework guide

### ISSUE THREAD

**Issue by hkennyv** [electron-forge/electron-forge-docs#39]
When following the instructions for the [React with Typescript framework integration guide](https://www.electronforge.io/guides/framework-integration/react-with-typescript), we get the following eslint error:

```
Unable to resolve path to module './app'. eslint(import/no-unresolved)
```

**To reproduce:**

- `yarn create electron-app my-new-app --template=typescript-webpack`
- `cd my-new-app`
- add `"jsx": "react"` to `tsconfig.json` under `"compilerOptions"`
- add react dependencies:

```
yarn add react react-dom
yarn add --dev @types/react @types/react-dom
```

- add the `src/app.tsx` file from the guide
- add the `import './app'` line to `src.renderer.ts`
- run `yarn lint` to view the error above

I was able to resolve this by adding `"plugin:import/typescript"` to the `.eslintrc.json` under the `"extends"` key. I'm working on an edit to the docs for a PR.

**Comment by malept** [comment]
This has been part of the template itself since beta 55.
