### ISSUE TITLE
 electron-forge about webpack 5 unable to use IPC

### ISSUE THREAD

**Issue by cby2566** [electron-forge/electron-forge-docs#50]
@electron-forge/plugin-webpack : "version": "6.0.0-beta.54".

**Comment by malept** [comment]
This issue tracker is for bugs and feature requests for the Electron Forge documentation, not for support for Electron Forge. Instead, consider using one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron), as there are more people there available to answer questions.
