### ISSUE TITLE
is nodeIntegration a boolean?

### ISSUE THREAD

**Issue by jayenashar** [electron-forge/electron-forge-docs#65]
https://www.electronforge.io/config/plugins/webpack#configuration says:

> The complete config options are available at [`WebpackPluginConfig`](https://js.electronforge.io/plugin/webpack/interfaces/webpackpluginconfig.html).

but i can't find any documentation on `nodeIntegration` on [`WebpackPluginConfig`](https://js.electronforge.io/plugin/webpack/interfaces/webpackpluginconfig.html).  i am trying to use openpgp.js and it isn't properly detecting which environment to run in and is giving an error.  i'd like to disable `nodeIntegration` for this package.

**Comment by georgexu99** [comment]
nodeIntegration is a boolean:

   *  When `nodeIntegration` is true, the `target` is `electron-renderer`.
   *  When `nodeIntegration` is false, the `target` is `web`.
   
   [This](https://github.com/electron-userland/electron-forge/blob/master/packages/plugin/webpack/src/Config.ts) may be of help if additional information is needed!

**Comment by jayenashar** [comment]
Thanks.  I was able to get openpgp working with this hack: https://github.com/openpgpjs/openpgpjs/discussions/1545

Can I convert this issue to a feature request?  Being able to set nodeIntegration for paths and not as a whole for the project?

**Comment by georgexu99** [comment]
https://github.com/electron-forge/electron-forge-docs/pull/68
https://github.com/electron-userland/electron-forge/pull/2867

Is this what you are looking for?

**Comment by jayenashar** [comment]
no.  more like this:

```json
        [
          "@electron-forge/plugin-webpack",
          {
            "devContentSecurityPolicy": "default-src * self blob: data: gap:; style-src * self 'unsafe-inline' blob: data: gap:; script-src * 'self' 'unsafe-eval' 'unsafe-inline' blob: data: gap:; object-src * 'self' blob: data: gap:; img-src * self 'unsafe-inline' blob: data: gap:; connect-src self * 'unsafe-inline' blob: data: gap:; frame-src * self blob: data: gap:;",
            "mainConfig": "./webpack.main.config.js",
            "renderer": {
              "nodeIntegration": ["**", "!./node_modules/openpgp"],
              "config": "./webpack.renderer.config.js",
              "entryPoints": [
                {
                  "html": "./src/index.html",
                  "js": "./src/renderer.js",
                  "name": "main_window"
                }
              ]
            }
          }
        ]
```

**Comment by erickzhao** [comment]
`nodeIntegration` applies to an entire renderer process and can't be isolated to specific Node.js modules. https://github.com/electron/forge/pull/2867 linked above adds the support to target individual processes as well. The value of this property will always be boolean.
