### ISSUE TITLE
https://www.electronforge.io/ is down

### ISSUE THREAD

**Issue by purefan** [electron-forge/electron-forge-docs#8]
```
* Could not resolve host: www.electronforge.io
* Closing connection 0
curl: (6) Could not resolve host: www.electronforge.io

```

**Comment by aperkaz** [comment]
Same issue here, cant access the webpage.

**Comment by aperkaz** [comment]
Same issue here, cant access the webpage.

![Screenshot at 2020-06-04 13-50-18](https://user-images.githubusercontent.com/16224847/83753402-81a46400-a66a-11ea-8fa0-4180aa987d81.png)

**Comment by malept** [comment]
Seems to be working now, probably a DNS problem that resolved itself.
