### ISSUE TITLE
Add clarity on how to use external node_modules with webpack

### ISSUE THREAD

**Issue by joezappie** [electron-forge/electron-forge-docs#91]
I think the guidance on how to deal with external node modules when using webpack could use some clarification. Specifically, my application uses serialport.io. To get this to work in dev, I had to add it as an external to webpack config:

```
externals: {
    serialport: "require('serialport')"
},
```

This however, did not work when building the application as it would then complain about serialport not being found. Looking through the build files, serialport was no where to be found.

After spending a few days on the issue, I finally found a stackoverflow post from a few months ago which describes the issue:

`If a module is listed as external, it will be pruned during the packaging process. So in your forge config, you need to include hooks during your building process.`

https://stackoverflow.com/questions/71930401/webpack-not-including-module-with-electron-forge-and-serialport

Even just having that quote somewhere in the build documentation would be very helpful.

After adding the hook to run `npm install` after prune, the built app runs without any issue.

```
hooks: {
    packageAfterPrune: async (forgeConfig, buildPath) => {
      console.log(buildPath);
      return new Promise((resolve, reject) => {
        const npmInstall = spawn("npm", ["install", "serialport"], {
          cwd: buildPath,
          stdio: "inherit",
          shell: true,
        });

        npmInstall.on("close", (code) => {
          if (code === 0) {
            resolve();
          } else {
            reject(new Error("process finished with error code " + code));
          }
        });

        npmInstall.on("error", (error) => {
          reject(error);
        });
      });
    },
  },
```

This, however, seems to install all the dependencies in package.json, not just the serialport module. This causes packaging to take a lot longer as theres lots of files to now copy over. Guidance on what the recommended approach to this would be much appreciated. 

I think a large source of confusion for me (and a lot of other people from the posts I've read) is assuming everything is being bundled automatically. Theres a lot of verbage in the docs currently saying this should mainly work out of the box but for the things that don't, I haven't been able to find any official documentation on what to do.

**Comment by MarshallOfSound** [comment]
@jrj2211 The "correct" way of handling issues with native modules not being bundled correctly, is to fix the native module itself as it's normally doing something Wrong ™️ or fix the tooling to handle the Weird Thing ™️ that the module is doing.

For serialport see this comment. https://github.com/electron/forge/issues/2949#issuecomment-1308323004
